apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ulwxbnn0e-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ulwxbnn0e-java-quarkus-gitops